<a href="https://colab.research.google.com/github/swapnilmn/Assignment_03/blob/main/Ass_03ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!yes | wget "https://drive.google.com/file/d/1uRKU4as2NlS9i8sdLRS1e326vQRdhvfw/view?usp=sharing"

--2023-05-17 11:49:35--  https://drive.google.com/file/d/1uRKU4as2NlS9i8sdLRS1e326vQRdhvfw/view?usp=sharing
Resolving drive.google.com (drive.google.com)... 173.194.194.102, 173.194.194.113, 173.194.194.101, ...
Connecting to drive.google.com (drive.google.com)|173.194.194.102|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘view?usp=sharing’

view?usp=sharing        [ <=>                ]  73.85K  --.-KB/s    in 0.001s  

2023-05-17 11:49:35 (55.7 MB/s) - ‘view?usp=sharing’ saved [75622]



In [3]:
from google.colab import drive
import pandas as pd
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


# Drafts

In [4]:
import pandas as pd

def load_data(path):
  """Loads the data from the specified path.

  Args:
    path: The path to the data file.

  Returns:
    A Pandas DataFrame containing the data.
  """

  with open(path) as fil:
    df = pd.read_csv(fil, sep=',', header=None, names=['en', 'ma', ''], skip_blank_lines=True, index_col=None)

  df = df[df['en'].notna()]
  df = df[df['ma'].notna()]
  df = df[['en', 'ma']]

  return df

train = load_data("/content/drive/MyDrive/aksharantar_sampled/aksharantar_sampled/mar/mar_train.csv")
val = load_data("/content/drive/MyDrive/aksharantar_sampled/aksharantar_sampled/mar/mar_valid.csv")
test = load_data("/content/drive/MyDrive/aksharantar_sampled/aksharantar_sampled/mar/mar_test.csv")

In [16]:
def unique_tokenize(data):
    english_tokens = set()
    marathi_tokens = set()

    for english, marathi in list(zip(data['en'].values, data['ma'].values)):
        for ch in english:
            english_tokens.add(ch)
        for ch in marathi:
            marathi_tokens.add(ch)

    english_tokens = sorted(list(english_tokens))
    marathi_tokens = sorted(list(marathi_tokens))

    return marathi_tokens, english_tokens

marathi_tokens , english_tokens = unique_tokenize(train)
print(english_tokens)
print(len(marathi_tokens))

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
63


In [17]:
def tokenize_map(data):
    e_vocab = set()
    m_vocab = set()

    for e, m in zip(data['en'].values, data['ma'].values):
        for ch in e:
            e_vocab.add(ch)
        for ch in m:
            m_vocab.add(ch)

    e_vocab = sorted(list(e_vocab))
    m_vocab = sorted(list(m_vocab))

    e_to_i = {ch: i + 1 for i, ch in enumerate(e_vocab)}
    m_to_i = {ch: i + 1 for i, ch in enumerate(m_vocab)}

    m_to_i[' '] = 0
    e_to_i[' '] = 0

    m_to_i[';'] = 65
    m_to_i['.'] = 66
    e_to_i[';'] = 27
    e_to_i['.'] = 28

    m_to_i['<unk>'] = 64

    return e_to_i, m_to_i

mar_token_map, eng_token_map = tokenize_map(train)
print(mar_token_map)
print(eng_token_map)
print('mar:',len(mar_token_map))
print('eng:',len(eng_token_map))

{'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5, 'f': 6, 'g': 7, 'h': 8, 'i': 9, 'j': 10, 'k': 11, 'l': 12, 'm': 13, 'n': 14, 'o': 15, 'p': 16, 'q': 17, 'r': 18, 's': 19, 't': 20, 'u': 21, 'v': 22, 'w': 23, 'x': 24, 'y': 25, 'z': 26, ' ': 0, ';': 27, '.': 28}
{'ँ': 1, 'ं': 2, 'ः': 3, 'अ': 4, 'आ': 5, 'इ': 6, 'ई': 7, 'उ': 8, 'ऊ': 9, 'ऋ': 10, 'ऍ': 11, 'ए': 12, 'ऐ': 13, 'ऑ': 14, 'ओ': 15, 'औ': 16, 'क': 17, 'ख': 18, 'ग': 19, 'घ': 20, 'च': 21, 'छ': 22, 'ज': 23, 'झ': 24, 'ञ': 25, 'ट': 26, 'ठ': 27, 'ड': 28, 'ढ': 29, 'ण': 30, 'त': 31, 'थ': 32, 'द': 33, 'ध': 34, 'न': 35, 'प': 36, 'फ': 37, 'ब': 38, 'भ': 39, 'म': 40, 'य': 41, 'र': 42, 'ल': 43, 'ळ': 44, 'व': 45, 'श': 46, 'ष': 47, 'स': 48, 'ह': 49, '़': 50, 'ा': 51, 'ि': 52, 'ी': 53, 'ु': 54, 'ू': 55, 'ृ': 56, 'ॅ': 57, 'े': 58, 'ै': 59, 'ॉ': 60, 'ो': 61, 'ौ': 62, '्': 63, ' ': 0, ';': 65, '.': 66, '<unk>': 64}
mar: 29
eng: 67


In [18]:

x = test['en'].values
y = test['ma'].values
x=';'+ x + '.'
y = ';'+y+'.'
#Getting max length
max_eng_len = max([len(i) for i in x])
max_mar_len = max([len(i) for i in y])
print(max_eng_len,max_mar_len)

30 22


In [26]:
dont change varibles, write code in other template for same task 
chnage local variables


def load_data(path):
    with open(path) as fil:
        data = pd.read_csv(fil, sep=',', header=None, names=["en", "ma", ""], skip_blank_lines=True, index_col=None)
    data = data[data['en'].notna()]
    data = data[data['ma'].notna()]
    data = data[['en', 'ma']]
    return data

train = load_data("/content/drive/MyDrive/aksharantar_sampled/aksharantar_sampled/mar/mar_train.csv")
val = load_data("/content/drive/MyDrive/aksharantar_sampled/aksharantar_sampled/mar/mar_valid.csv")
test = load_data("/content/drive/MyDrive/aksharantar_sampled/aksharantar_sampled/mar/mar_test.csv")

def unique_tokenize(data):
    english = data['en'].values
    marathi = data['ma'].values
    english_tokens = set()
    marathi_tokens = set()

    for x, y in zip(english, marathi):
        for ch in x:
            english_tokens.add(ch)
        for ch in y:
            marathi_tokens.add(ch)
    english_tokens = sorted(list(english_tokens))
    marathi_tokens = sorted(list(marathi_tokens))
    return marathi_tokens, english_tokens

marathi_tokens, english_tokens = unique_tokenize(train)

def tokenize_map(marathi_tokens, english_tokens):
    marathi_token_map = dict([(ch, i + 1) for i, ch in enumerate(marathi_tokens)])
    english_token_map = dict([(ch, i + 1) for i, ch in enumerate(english_tokens)])
    marathi_token_map[" "] = 0
    english_token_map[" "] = 0
    marathi_token_map[';'] = 65
    marathi_token_map['.'] = 66
    english_token_map[';'] = 27
    english_token_map['.'] = 28
    marathi_token_map['<unk>'] = 64

    return marathi_token_map, english_token_map

mar_token_map, eng_token_map = tokenize_map(marathi_tokens, english_tokens)

unknown_token = 64

x = test['en'].values
y = test['ma'].values
x=';'+ x + '.'
y = ';'+y+'.'
#Getting max length
max_eng_len = max([len(i) for i in x])
max_mar_len = max([len(i) for i in y])
print(max_eng_len,max_mar_len)

def process(data):
    x, y = data['en'].values, data['ma'].values
    x = ";" + x + "."
    y = ";" + y + "."
    print(x[0:3])
    print(y[0:3]) 

    a = torch.zeros((len(x), max_eng_len), dtype=torch.int64)
    b = torch.zeros((len(y), max_eng_len), dtype=torch.int64)
    
    data = []
    for i, (xx, yy) in enumerate(zip(x, y)):
        for j, ch in enumerate(xx):
            a[i, j] = eng_token_map[ch]
        
        for j, ch in enumerate(yy):
            if ch in mar_token_map: 
                b[i, j] = mar_token_map[ch]
            else:
                b[i, j] = unknown_token
        
        data.append((a[i], b[i]))
    data = [(a[i], b[i]) for i in range(len(x))]
    print(a.shape)
    print(b.shape)
    return data

train_process = process(train)
val_process = process(val)
test_process = process(test)

print('\n')
print('num of rows:', len(train_process))
print('num of columns:', len(train_process[0]))
print(train_process[0][1])


30 22
[';fusharun.' ';bhulthapana.' ';vhayaki.']
[';फुशारुन.' ';भूलथापाना.' ';व्हायकी.']
torch.Size([51200, 30])
torch.Size([51200, 30])
[';garvyabarobarach.' ';reo.' ';sangrahalaye.']
[';गारव्याबरोबरच.' ';रियो.' ';संग्रहालये.']
torch.Size([4096, 30])
torch.Size([4096, 30])
[';heetler.' ';kshama.' ';jinkta.']
[';हिटलर.' ';क्षमा.' ';जिंकता.']
torch.Size([4096, 30])
torch.Size([4096, 30])


num of rows: 51200
num of columns: 2
tensor([65, 37, 54, 46, 51, 42, 54, 35, 66,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0])


In [31]:
import pandas as pd
import torch

def load_data(path):
    with open(path) as fil:
        data = pd.read_csv(fil, sep=',', header=None, names=["en", "ma", ""], skip_blank_lines=True, index_col=None)
    data = data[data['en'].notna()]
    data = data[data['ma'].notna()]
    data = data[['en', 'ma']]
    return data

train_data = load_data("/content/drive/MyDrive/aksharantar_sampled/aksharantar_sampled/mar/mar_train.csv")
val_data = load_data("/content/drive/MyDrive/aksharantar_sampled/aksharantar_sampled/mar/mar_valid.csv")
test_data = load_data("/content/drive/MyDrive/aksharantar_sampled/aksharantar_sampled/mar/mar_test.csv")

def unique_tokenize(data):
    english = data['en'].values
    marathi = data['ma'].values
    english_tokens = set()
    marathi_tokens = set()

    for x, y in zip(english, marathi):
        for ch in x:
            english_tokens.add(ch)
        for ch in y:
            marathi_tokens.add(ch)
    english_tokens = sorted(list(english_tokens))
    marathi_tokens = sorted(list(marathi_tokens))
    return marathi_tokens, english_tokens

marathi_tokens, english_tokens = unique_tokenize(train_data)

def tokenize_map(marathi_tokens, english_tokens):
    marathi_token_map = dict([(ch, i + 1) for i, ch in enumerate(marathi_tokens)])
    english_token_map = dict([(ch, i + 1) for i, ch in enumerate(english_tokens)])
    marathi_token_map[" "] = 0
    english_token_map[" "] = 0
    marathi_token_map[';'] = 65
    marathi_token_map['.'] = 66
    english_token_map[';'] = 27
    english_token_map['.'] = 28
    marathi_token_map['<unk>'] = 64

    return marathi_token_map, english_token_map

marathi_token_map, english_token_map = tokenize_map(marathi_tokens, english_tokens)

unknown_token = 64

x = test_data['en'].values
y = test_data['ma'].values
x = ';' + x + '.'
y = ';' + y + '.'

# Getting max length
max_eng_len = max([len(i) for i in x])
max_mar_len = max([len(i) for i in y])
print(max_eng_len, max_mar_len)

def process(data):
    x_values, y_values = data['en'].values, data['ma'].values
    x_values = ';' + x_values + '.'
    y_values = ';' + y_values + '.'
    print(x_values[0:3])
    print(y_values[0:3]) 

    a = torch.zeros((len(x_values), max_eng_len), dtype=torch.int64)
    b = torch.zeros((len(y_values), max_eng_len), dtype=torch.int64)

    processed_data = []
    for i, (xx, yy) in enumerate(zip(x_values, y_values)):
        for j, ch in enumerate(xx):
            a[i, j] = eng_token_map[ch]

        for j, ch in enumerate(yy):
            if ch in mar_token_map:
                b[i, j] = mar_token_map[ch]
            else:
                b[i, j] = unknown_token

        processed_data.append((a[i], b[i]))
    processed_data = [(a[i], b[i]) for i in range(len(x_values))]
    print(a.shape)
    print(b.shape)
    return processed_data

train_processed = process(train_data)
val_processed = process(val_data)
test_processed = process(test_data)

print('\n')
print('Number of rows:', len(train_processed))
print('Number of columns:', len(train_processed[0]))
print(train_processed[0][1])


30 22
[';fusharun.' ';bhulthapana.' ';vhayaki.']
[';फुशारुन.' ';भूलथापाना.' ';व्हायकी.']
torch.Size([51200, 30])
torch.Size([51200, 30])
[';garvyabarobarach.' ';reo.' ';sangrahalaye.']
[';गारव्याबरोबरच.' ';रियो.' ';संग्रहालये.']
torch.Size([4096, 30])
torch.Size([4096, 30])
[';heetler.' ';kshama.' ';jinkta.']
[';हिटलर.' ';क्षमा.' ';जिंकता.']
torch.Size([4096, 30])
torch.Size([4096, 30])


Number of rows: 51200
Number of columns: 2
tensor([65, 37, 54, 46, 51, 42, 54, 35, 66,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0])


In [32]:
Use class template 
change function names make code long

def load_data(path):
    with open(path) as fil:
        data = pd.read_csv(fil, sep=',', header=None, names=["en", "ma", ""], skip_blank_lines=True, index_col=None)
    data = data[data['en'].notna()]
    data = data[data['ma'].notna()]
    data = data[['en', 'ma']]
    return data

train_data = load_data("/content/drive/MyDrive/aksharantar_sampled/aksharantar_sampled/mar/mar_train.csv")
val_data = load_data("/content/drive/MyDrive/aksharantar_sampled/aksharantar_sampled/mar/mar_valid.csv")
test_data = load_data("/content/drive/MyDrive/aksharantar_sampled/aksharantar_sampled/mar/mar_test.csv")

def unique_tokenize(data):
    e = data['en'].values
    m = data['ma'].values
    e_tokens = set()
    m_tokens = set()

    for x, y in zip(e, m):
        for ch in x:
            e_tokens.add(ch)
        for ch in y:
            m_tokens.add(ch)
    e_tokens = sorted(list(e_tokens))
    m_tokens = sorted(list(m_tokens))
    return m_tokens, e_tokens

m_tokens, e_tokens = unique_tokenize(train_data)

def tokenize_map(m_tokens, e_tokens):
    m_token_map = dict([(ch, i + 1) for i, ch in enumerate(m_tokens)])
    e_token_map = dict([(ch, i + 1) for i, ch in enumerate(e_tokens)])
    m_token_map[" "] = 0
    e_token_map[" "] = 0
    m_token_map[';'] = 65
    m_token_map['.'] = 66
    e_token_map[';'] = 27
    e_token_map['.'] = 28
    m_token_map['<unk>'] = 64

    return m_token_map, e_token_map

m_token_map, e_token_map = tokenize_map(m_tokens, e_tokens)

unknown_token = 64

x = test_data['en'].values
y = test_data['ma'].values
x = ';' + x + '.'
y = ';' + y + '.'

# Getting max length
max_e_len = max([len(i) for i in x])
max_m_len = max([len(i) for i in y])
print(max_e_len, max_m_len)

def process(data):
    x_vals, y_vals = data['en'].values, data['ma'].values
    x_vals = ';' + x_vals + '.'
    y_vals = ';' + y_vals + '.'
    print(x_vals[0:3])
    print(y_vals[0:3]) 

    a = torch.zeros((len(x_vals), max_e_len), dtype=torch.int64)
    b = torch.zeros((len(y_vals), max_e_len), dtype=torch.int64)

    processed_data = []
    for i, (xx, yy) in enumerate(zip(x_vals, y_vals)):
        for j, ch in enumerate(xx):
            a[i, j] = e_token_map[ch]

        for j, ch in enumerate(yy):
            if ch in m_token_map:
                b[i, j] = m_token_map[ch]
            else:
                b[i, j] = unknown_token

        processed_data.append((a[i], b[i]))
    processed_data = [(a[i], b[i]) for i in range(len(x_vals))]
    print(a.shape)
    print(b.shape)
    return processed_data

train_processed = process(train_data)
val_processed = process(val_data)
test_processed = process(test_data)

print('\n')
print('Number of rows:', len(train_processed))
print('Number of columns:', len(train_processed[0]))
print(train_processed[0][1])


30 22
[';fusharun.' ';bhulthapana.' ';vhayaki.']
[';फुशारुन.' ';भूलथापाना.' ';व्हायकी.']
torch.Size([51200, 30])
torch.Size([51200, 30])
[';garvyabarobarach.' ';reo.' ';sangrahalaye.']
[';गारव्याबरोबरच.' ';रियो.' ';संग्रहालये.']
torch.Size([4096, 30])
torch.Size([4096, 30])
[';heetler.' ';kshama.' ';jinkta.']
[';हिटलर.' ';क्षमा.' ';जिंकता.']
torch.Size([4096, 30])
torch.Size([4096, 30])


Number of rows: 51200
Number of columns: 2
tensor([65, 37, 54, 46, 51, 42, 54, 35, 66,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0])


# Data Processing

In [41]:
import pandas as pd
import torch

class DataLoader:
    def __init__(self, train_path, val_path, test_path):
        self.train_data = self.load_data(train_path)
        self.val_data = self.load_data(val_path)
        self.test_data = self.load_data(test_path)
        self.m_token_map, self.e_token_map = self.tokenize_map(self.unique_tokenize(self.train_data))
        self.max_e_len, self.max_m_len = self.get_max_lengths(self.test_data['en'].values, self.test_data['ma'].values)
        self.unknown_token = 64

    def load_data(self, path):
        with open(path) as fil:
            data = pd.read_csv(fil, sep=',', header=None, names=["en", "ma", ""], skip_blank_lines=True, index_col=None)
        data = data[data['en'].notna()]
        data = data[data['ma'].notna()]
        data = data[['en', 'ma']]
        return data

    def unique_tokenize(self, data):
        e = data['en'].values
        m = data['ma'].values
        e_tokens = set()
        m_tokens = set()

        for x, y in zip(e, m):
            for ch in x:
                e_tokens.add(ch)
            for ch in y:
                m_tokens.add(ch)
        e_tokens = sorted(list(e_tokens))
        m_tokens = sorted(list(m_tokens))
        return m_tokens, e_tokens

    def tokenize_map(self, tokens):
        m_tokens, e_tokens = tokens
        m_token_map = dict([(ch, i + 1) for i, ch in enumerate(m_tokens)])
        e_token_map = dict([(ch, i + 1) for i, ch in enumerate(e_tokens)])
        m_token_map[" "] = 0
        e_token_map[" "] = 0
        m_token_map[';'] = 65
        m_token_map['.'] = 66
        e_token_map[';'] = 27
        e_token_map['.'] = 28
        m_token_map['<unk>'] = 64

        return m_token_map, e_token_map

    def get_max_lengths(self, x_vals, y_vals):
        x = ';' + x_vals + '.'
        y = ';' + y_vals + '.'
        max_e_len = max([len(i) for i in x])
        max_m_len = max([len(i) for i in y])
        return max_e_len, max_m_len

    def process(self, data):
        x_vals, y_vals = data['en'].values, data['ma'].values
        x_vals = ';' + x_vals + '.'
        y_vals = ';' + y_vals + '.'
        print(x_vals[0:3])
        print(y_vals[0:3]) 

        a = torch.zeros((len(x_vals), self.max_e_len), dtype=torch.int64)
        b = torch.zeros((len(y_vals), self.max_e_len), dtype=torch.int64)

        processed_data = []
        for i, (xx, yy) in enumerate(zip(x_vals, y_vals)):
            for j, ch in enumerate(xx):
                a[i, j] = self.e_token_map[ch]

            for j, ch in enumerate(yy):
                if ch in self.m_token_map:
                    b[i, j] = self.m_token_map[ch]
                else:
                    b[i, j] = self.unknown_token

            processed_data.append((a[i], b[i]))
        processed_data = [(a[i], b[i]) for i in range(len(x_vals))]
        return processed_data

    def print_summary(self):
        train_processed = self.process(self.train_data)
        val_processed = self.process(self.val_data)
        test_processed = self.process(self.test_data)

        print('\n')
        print('Number of rows:', len(train_processed))
        print('Number of columns:', len(train_processed[0]))
        print(train_processed[0][1])


# Example usage
data_loader = DataLoader(
    "/content/drive/MyDrive/aksharantar_sampled/aksharantar_sampled/mar/mar_train.csv",
    "/content/drive/MyDrive/aksharantar_sampled/aksharantar_sampled/mar/mar_valid.csv",
    "/content/drive/MyDrive/aksharantar_sampled/aksharantar_sampled/mar/mar_test.csv"
)

data_loader.print_summary()


[';fusharun.' ';bhulthapana.' ';vhayaki.']
[';फुशारुन.' ';भूलथापाना.' ';व्हायकी.']
[';garvyabarobarach.' ';reo.' ';sangrahalaye.']
[';गारव्याबरोबरच.' ';रियो.' ';संग्रहालये.']
[';heetler.' ';kshama.' ';jinkta.']
[';हिटलर.' ';क्षमा.' ';जिंकता.']


Number of rows: 51200
Number of columns: 2
tensor([65, 37, 54, 46, 51, 42, 54, 35, 66,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0])
